version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: live-audio-api
    restart: unless-stopped
    profiles:
      - app
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: live-audio-worker
    restart: unless-stopped
    profiles:
      - app
    env_file:
      - .env
    command: ["node", "./src/worker.js"]
    depends_on:
      - postgres
      - redis

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: live-audio-scheduler
    restart: unless-stopped
    profiles:
      - app
    env_file:
      - .env
    command: ["node", "./src/scheduler.js"]
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    container_name: live-audio-postgres
    restart: unless-stopped
    profiles:
      - infra
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: live_audio
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: live-audio-redis
    restart: unless-stopped
    profiles:
      - infra
    ports:
      - "6379:6379"
  livekit:
    image: livekit/livekit-server:latest
    platform: linux/arm64/v8
    container_name: livekit-server
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    profiles:
      - livekit
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml:ro

  nginx-rtmp:
    image: tiangolo/nginx-rtmp:latest
    platform: linux/arm64/v8
    container_name: nginx-rtmp
    restart: unless-stopped
    profiles:
      - hls
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - ./dev/nginx-rtmp.conf:/etc/nginx/nginx.conf:ro
      - ./hls:/var/www/hls

volumes:
  pg_data:
